vaadin.launch-browser=true
spring.application.name=foodly-ai

# Chave da OpenAI via variável de ambiente
spring.ai.openai.api-key=${OPENAI_API_KEY}

# Modelo a ser utilizado
spring.ai.openai.chat.options.model=gpt-4o-mini

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
